build:
  version: "3.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pocketshield
    username: root
    password: Water123##Water123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: http://localhost:8180/realms/pocketshield/protocol/openid-connect/certs
  port: 8081



