build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pocketshield
    username: root
    password: "{cipher}da7007a103a71cde83448bb70d19806c1ad648d9452148d837df3013e07d1146cd225efa7fbd60d60aee7196847a2f12"

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8081
